---
abstract: 'subroutine signatures with no source filter'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  B::Hooks::OP::Check: 0.17
  B::Hooks::OP::PPAddr: 0
  B::Hooks::Parser: 0.07
  ExtUtils::MakeMaker: 6.42
configure_requires:
  B::Hooks::OP::Check: 0.17
  B::Hooks::OP::PPAddr: 0
  B::Hooks::Parser: 0.07
  ExtUtils::Depends: 0
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.84'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: signatures
no_index:
  directory:
    - inc
    - t
requires:
  B::Hooks::OP::Check: 0.17
  B::Hooks::OP::PPAddr: 0
  B::Hooks::Parser: 0.07
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=signatures
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rafl/signatures.git
version: 0.04
